from setuptools import find_namespace_packages, setup

packages = [
    package for package in find_namespace_packages(
        where='./src', include='ciandt.google_cloud.*')
]

setup(
    name='metrics_collector',
    author='Marcelo Costa',
    author_email='mmiranda@ciandt.com',
    version='0.0.1',
    description=
    'Library for collecting metrics generated by Datacatalog Connectors',
    platforms='Posix; MacOS X; Windows',
    packages=packages,
    package_dir={'': 'src'},
    include_package_data=True,
    install_requires=(
        'pandas',
    ),
    setup_requires=('pytest-runner',),
    tests_require=('pytest-cov',),
    classifiers=(
        'Development Status :: 1 - Alpha',
        'Programming Language :: Python :: 3.7',
    ),
)
